language: node_js
node_js:
  - "0.10"

notifications:
  email:
    - bartvanderschoor@gmail.com

branches:
  only:
    - develop-0.5.x
    - develop-0.4.x
    - master
    - travis-debug

env:
  - TRAVIS=true
